-- MySQL Script generated by MySQL Workbench
-- mar 28 abr 2015 18:35:35 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pdv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pdv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pdv` DEFAULT CHARACTER SET latin1 ;
USE `pdv` ;

-- -----------------------------------------------------
-- Table `pdv`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdv`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `password` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `activador` INT(11) NOT NULL,
  `numsuc` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pdv`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdv`.`sucursales` (
  `id_sucursal` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_sucursal`),
  INDEX `id_usuario` (`id_usuario` ASC),
  CONSTRAINT `sucursales_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `pdv`.`usuarios` (`id_usuario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pdv`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdv`.`empleados` (
  `id_empleado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  `id_sucursal` INT(11) NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `id_sucursal` (`id_sucursal` ASC),
  CONSTRAINT `empleados_ibfk_1`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `pdv`.`sucursales` (`id_sucursal`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pdv`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdv`.`productos` (
  `id_productos` INT(11) NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(50) NOT NULL,
  `imagen` TEXT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `id_sucursal` INT(11) NOT NULL,
  `codigo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_productos`),
  INDEX `id_sucursal` (`id_sucursal` ASC),
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `pdv`.`sucursales` (`id_sucursal`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pdv`.`telempleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdv`.`telempleados` (
  `telefono` VARCHAR(20) NOT NULL,
  `id_empleado` INT(11) NOT NULL,
  INDEX `id_empleado` (`id_empleado` ASC),
  CONSTRAINT `telempleados_ibfk_1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `pdv`.`empleados` (`id_empleado`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pdv`.`telesucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdv`.`telesucursales` (
  `telefono` VARCHAR(20) NOT NULL,
  `id_sucursal` INT(11) NOT NULL,
  INDEX `id_sucursal` (`id_sucursal` ASC),
  CONSTRAINT `telesucursales_ibfk_1`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `pdv`.`sucursales` (`id_sucursal`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
